x-common-service-build: &common-service-build
  context: skillpath-backend
  target: runner

services:
  database:
    image: postgres:18-alpine
    hostname: database
    container_name: test_database
    restart: unless-stopped
    env_file:
      - .env.production.local

  redis:
    image: redis:8-alpine
    hostname: redis
    container_name: test_redis
    restart: unless-stopped
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]

  bff:
    depends_on:
      auth:
        condition: service_healthy
      courses:
        condition: service_healthy
    healthcheck:
      test: [ 'CMD', 'curl', '-fsS', 'http://localhost:3001/health/live' ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 15s
    build:
      context: skillpath-backend
      target: e2e
      args:
        SERVICE_NAME: bff
        HTTP_PORT: 3001
    hostname: bff
    container_name: test_bff_service
    env_file:
      - skillpath-backend/apps/bff/.env.test.local

  auth:
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
    healthcheck:
      test: [ 'CMD', 'curl', '-fsS', 'http://localhost:3002/health/ready' ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 15s
    build:
      <<: *common-service-build
      args:
        SERVICE_NAME: auth
        HTTP_PORT: 3002
    hostname: auth_service
    container_name: test_auth_service
    env_file:
      - skillpath-backend/apps/auth/.env.test.local

  courses:
    depends_on:
      database:
        condition: service_started
    healthcheck:
      test: [ 'CMD', 'curl', '-fsS', 'http://localhost:3003/health/ready' ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 15s
    build:
      <<: *common-service-build
      args:
        SERVICE_NAME: courses
        HTTP_PORT: 3003
    hostname: courses_service
    container_name: test_courses_service
    env_file:
      - skillpath-backend/apps/courses/.env.test.local